### ISSUE TITLE
Is this framework async?

### ISSUE THREAD

**Issue by leenux** [DavidArno/SuccincT#14]
I can't find the framework async oper.

**Comment by DavidArno** [comment]
There currently aren't any async features within the library as I've not yet identified any need for them.

What particular features do you feel would benefit from async support?

**Comment by leenux** [comment]
Yes,I think so.
There are many systems that are constructed in an asynchronous fashion. The asynchronous system expects all components to be asynchronous to achieve a non blocking purpose.

**Comment by DavidArno** [comment]
I'm still unsure what you are asking for. As none of Succinc&lt;T&gt;'s APIs are blocking in nature, adding `async` to those APIs would just make them slower. "*The asynchronous system expects all components to be asynchronous to achieve a non blocking purpose*" doesn't sound right to me. You only want routes through to blocking components to be async-based. 

What specifically is it that you wish to do with Succinc&lt;T&gt;? How would that use relate to async functionality? I need a bit more info please in order to understand what - if any - changes could be made to better support async.

**Comment by DavidArno** [comment]
Closing this as it's unclear what's needed.

@leenux,
If you get a chance to clarify what you are asking for, I'll reopen it.

**Comment by DavidArno** [comment]
Re-opening this issue.

There is benefit in me exploring supporting async lambdas/methods in pattern matching, `Ignore` and the like.

**Comment by DavidArno** [comment]
Have concluded (likely through ignorance) that explicit async support isn't needed and that Succinc\<T\> works with async.
