### ISSUE TITLE
Preparation for v3.1 release

### ISSUE THREAD

**Issue by DavidArno** [DavidArno/SuccincT#46]
The following tasks need completing, in order to release v3.1:

**Coding**
- [x] ~~Add missing tests for `Copy()`~~
- [x] ~~Agree naming/behaviour of `With` and `Copy` with @Odonno and add extra methods as required~~
- [x] Check code against R#'s code inspections and implement any improvements

**Documentation**
- [x] `Deconstruct` for `Option`, `Maybe` and `Success` types
- [x] `ValueOrDefault` for `Option` and `Maybe` types
- [x] Pattern matching for `Success` type
- [ ] Cons pattern matching
- [x]  Accessing Union values directly (@peter-majeed contribution)
- [x] ~~`With` and `Copy` extensions (@Odonno contribution)~~
- [x] Add @Odonno and @peter-majeed to the contributor list
- [x] Update release notes, version history and readme as required

**Release**
- [x] Create v4.0 branch from v3.1.
- [x] Remove `Copy` and `With` from the v3.1 branch
- [x] Merge to `master`
- [x] Add performance testing project back into solution (on v4.0 branch only!)
- [x] Push `master`; package and publish nuget packages
- [x] Push wiki changes
- [x] And relax...

**Comment by peter-majeed** [comment]
@DavidArno thanks for pushing this forward! I put together the markup for the documentation of the `Union.Value<TResult>` method. Let me know if I can help out with anything else there.

----

### Imperative Use ###
As an alternative to using a union in a functional style, its value can be directly accessed by more traditional, imperative style C# code. One method and three read-only properties are provided for this purpose:

#### Value<TResult> ####
````csharp
public TResult Value<TResult>()
````
Returns the value of the union directly. If the value of the union is not of the `TResult` type, an `InvalidOperationException` will be thrown.

#### Case ####

````csharp
public Variant Case { get; }
````
Returns `Variant.Case1` if the value is of `T1` or `Variant.Case2` if the value is of `T2`.

#### Case1 ####

````csharp
public T1 Case1 { get; }
````

If `Case` is `Variant.Case1`, this will return the value held by the union. Otherwise an `InvalidOperationException` will be thrown.


#### Case2 ####

````csharp
public T2 Case2 { get; }
````

If `Case` is `Variant.Case2`, this will return the value held by the union. Otherwise an `InvalidOperationException` will be thrown.

**Comment by peter-majeed** [comment]
@DavidArno is there any way we can help with any of the remaining tasks? We're trying to use the `Case<>` method sooner rather than later, but we'd rather not fork the repo in our private nuget feed.

**Comment by Odonno** [comment]
Yes. Count me in if you want help to complete this release. Not sure if I can really be helpful but we can discuss about it together.

**Comment by DavidArno** [comment]
@peter-majeed & @Odonno,

My apologies for the huge delay. I have been tied up in a major house renovation for the last few months and will continue to be tied up until the end of March. As such, I've not really been able to devote any time to SuccincT. However, checking things, I realised that all that was holding up the release was documenting the cons pattern matching. So I've decided to leave that unfinished and release v3.1. It should appear on the nuget server in the next hour or so.

Once again, apologies for the delays.

**Comment by DavidArno** [comment]
Oh and thanks to you both for your offers of help. Knowing that people cared that much spurred me on to putting a bit of effort in to getting v3.1 out. Thanks, both.

**Comment by peter-majeed** [comment]
No problem, @DavidArno, things look good here!

**Comment by Odonno** [comment]
@DavidArno I hope you're fine. Can we plan a release date for 4.0?
