### ISSUE TITLE
When will version 3.1.1 be published to NuGet?

### ISSUE THREAD

**Issue by kgreen24** [DavidArno/SuccincT#55]
The merged enhancement of adding HasValue<T> to unions is something my team would like to utilize as soon as possible.

Thanks.

**Comment by DavidArno** [comment]
To be honest, I hadn't planned to. I was going to focus on v4. But since you asked so nicely... 😉 

In reality, I have a couple of spare evenings, today and tomorrow. So it should be feasible to create the release during that time for you. I'll therefore create a v3.2 (as your PRs include a new feature).

**Comment by kgreen24** [comment]
That's awesome, thank you!

**Comment by DavidArno** [comment]
Hi,

v3.2 is now available on nuget. Please let me know if you have any problems with it.

I went with `HasValueOf<T>` as I felt that fitted better with the `CaseOf<T>` feature in union pattern matching.
